/**
 * createEntry hook — not generated by orval, added manually.
 * POST /api/entries → create a new entry for a participant (maks 3 per akun)
 */
import { useMutation } from '@tanstack/react-query';
import type {
  MutationFunction,
  UseMutationOptions,
  UseMutationResult,
} from '@tanstack/react-query';

import { customFetch } from './custom-fetch';
import type { BodyType, ErrorType } from './custom-fetch';
import type { EntryInput, EntryResult } from './generated/api.schemas';

export const createEntry = async (
  entryInput: EntryInput,
  options?: RequestInit,
): Promise<EntryResult> => {
  return customFetch<EntryResult>('/api/entries', {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(entryInput),
  });
};

export const useCreateEntry = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      EntryResult,
      TError,
      { data: BodyType<EntryInput> },
      TContext
    >;
  },
): UseMutationResult<EntryResult, TError, { data: BodyType<EntryInput> }, TContext> => {
  const mutationFn: MutationFunction<EntryResult, { data: BodyType<EntryInput> }> = (
    props,
  ) => {
    const { data } = props ?? {};
    return createEntry(data);
  };

  return useMutation({
    mutationKey: ['createEntry'],
    mutationFn,
    ...options?.mutation,
  });
};
